name: ci

on:
  - push

jobs:
  tests:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    strategy:
      fail-fast: true
    steps:
      - name: Checkout recurly-java-library
        uses: actions/checkout@v2
      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        run: |
          mvn clean test -Ptravis -Dkillbill.payment.recurly.apiKey=$API_KEY -Dkillbill.payment.recurly.subDomain=$SUBDOMAIN
